definitions:
  tasks_domain.Task:
    properties:
      id:
        type: string
      name:
        type: string
      status:
        type: string
    required:
    - name
    - status
    type: object
info:
  contact: {}
  title: backend api with go
paths:
  /tasks:
    get:
      description: Get all tasks from the system.
      operationId: get-all-tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/tasks_domain.Task'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all tasks.
    post:
      consumes:
      - application/json
      description: Create a new task with the data provided in the JSON body
      parameters:
      - description: Data of the new task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/tasks_domain.Task'
      produces:
      - application/json
      responses:
        "200":
          description: Inserted task
          schema:
            $ref: '#/definitions/tasks_domain.Task'
        "400":
          description: Error in input data
          schema:
            $ref: '#/definitions/tasks_domain.Task'
        "500":
          description: Error in input data
          schema:
            $ref: '#/definitions/tasks_domain.Task'
      summary: Create a new task
  /tasks/{id}:
    delete:
      description: Delete a task from the system using its ID.
      operationId: delete-task
      parameters:
      - description: ID of the task to delete
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete a task by ID.
    put:
      consumes:
      - application/json
      description: Update a task in the system using its ID and the new provided data.
      operationId: update-task
      parameters:
      - description: ID of the task to update
        in: path
        name: id
        required: true
        type: string
      - description: New data of the task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/tasks_domain.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update a task by ID.
swagger: "2.0"
