name: 'Unit testing y Code Coverage'
on: 
  workflow_call:
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL:
        required: true
      

jobs:
  code-coverage:  
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.0'

      - name: Run Unit Testing With Code Coverage
        run: |
          go test ./... -coverprofile=c.out
          go tool cover -html="c.out"

      - name: Convert coverage to Cobertura format
        run: |
          go install github.com/t-yuki/gocover-cobertura@latest
          gocover-cobertura < coverage.out > coverage.xml
      
      - name: Check coverage threshold
        uses: tj-actions/coverage-check@v2
        with:
          file: coverage.xml
          threshold: 70

      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: 'Unit testing y Code Coverage'
          subtitle: ${{ github.event.pull_request.head.ref }}



