name: 'Unit testing y Code Coverage'
on: 
  workflow_call:
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL:
        required: true
      

jobs:
  code-coverage:  
    runs-on: ubuntu-latest
    environment: development
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Run tests and check coverage
        run: |
          chmod +x ./test.sh
          ./test.sh

      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: 'Unit testing y Code Coverage'
          subtitle: ${{ github.event.pull_request.head.ref }}



