name: 'Code Quality With Code Climate'

on:
  workflow_call:
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL:
        required: true
jobs:
  code-quality:  
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Use Code Climate CLI
        run: |
          mkdir -p ${{ github.workspace }}/../codeclimate
          curl -L https://github.com/codeclimate/codeclimate/archive/master.tar.gz | tar xvz
          cd codeclimate-* && sudo make install 
          cd ${{ github.workspace }} && pwd && codeclimate analyze -f html > code-quality.html

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-quality
          path: code-quality.html
      
      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: 'Code quality'
          subtitle: ${{ github.event.pull_request.head.ref }}




