name: OWASP Dependency-Check

on:
  workflow_call:
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL:
        required: true

jobs:
  dependency-check:
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Dependency-Check
        run: |
          curl -sSfL https://get-dependency-check.sh | sh
          dependency-check --scan ./ --out . --format ALL

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report.html
      
      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: 'OWASP Dependency-Check'
          subtitle: ${{ github.event.pull_request.head.ref }}
