name: Dependency-Check

on:
  workflow_call:
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL:
        required: true

jobs:
  dependency-check:
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.23.0
          go-package: ./...
          output-format: text
          output-file: vuln-check-1.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.head_ref }}-${{ github.event.pull_request.number }}
          path: vuln-check.txt
          overwrite: true
      
      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: 'Dependency-Check'
          subtitle: ${{ github.event.pull_request.head.ref }}