name: Deploy Dev
on:
  workflow_call:
    secrets:
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      SERVICE_ACCOUNT:
        required: true
      CLOUD_REGISTRY:
        required: true
      DB_HOST:
        required: true
      DB_PASSWORD:
        required: true
      GOOGLE_CHAT_WEBHOOK_URL:
        required: true
      SERVICE_NAME:
        required: true
      IMAGE_TAG:
        required: true
      VPC_CONNECTOR:
        required: true
      DB_NAME:
        required: true
jobs:
  gcp:
    environment: development
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      
      - name: 'Deploy Image'
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }}-${{ github.event.pull_request.number }} --image ${{ secrets.CLOUD_REGISTRY }}:${{ secrets.IMAGE_TAG }} --region us-east4 --port 8080 --allow-unauthenticated --set-env-vars context=postgres,DB_STRING="host=${{ secrets.DB_HOST }} user=postgres password=${{ secrets.DB_PASSWORD }} dbname=${{ secrets.DB_NAME }} port=5432 sslmode=disable" --vpc-connector ${{ secrets.VPC_CONNECTOR }}

      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: 'Deploy dev'
          subtitle: ${{ github.event.pull_request.head.ref }}
