name: 'Go Lint'
on: 
  workflow_call:
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL:
        required: true

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    environment: development
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --timeout=30m > golangci-lint-output.txt

      - name: Upload golangci-lint output
        uses: actions/upload-artifact@v4
        with:
          name: QA Results
          path: golangci-lint-output.txt
                
      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: 'GO Lint'
          subtitle: ${{ github.event.pull_request.head.ref }}