name: 'Github Demo CI/CD'
on: 
  push:
    branches:
      - develop

jobs:
  container-scanning:
    uses: hermes-logistic/demo-pipelines/.github/workflows/container-scanning.yaml@develop
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

  dependency-check:
    uses: hermes-logistic/demo-pipelines/.github/workflows/dependency-scanner.yaml@develop
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

  code-coverage:
    needs: [container-scanning, dependency-check]
    uses: hermes-logistic/demo-pipelines/.github/workflows/code-coverage.yaml@develop
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

  code-quality:
    needs: [container-scanning, dependency-check]
    uses: hermes-logistic/demo-pipelines/.github/workflows/code-quality.yaml@develop
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

  go-lint:
    needs: [container-scanning, dependency-check]
    permissions:
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read
    uses: hermes-logistic/demo-pipelines/.github/workflows/golangci-lint.yml@develop
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

