name: 'Reviwer App'

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  create-cr:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Create DB'
        run: |
          gcloud sql databases create ${{ github.repository }}-${{ github.event.pull_request.head.ref }} --instance=reviwer-db

      - name: 'Build Image'
        run: |
          gcloud auth configure-docker us-east4-docker.pkg.dev
          docker build -t ${{ secrets.CLOUD_REGISTRY }}:test --cache-from ${{ secrets.CLOUD_REGISTRY }}:test .
      
      - name: 'Push Image'
        run: |
          docker push ${{ secrets.CLOUD_REGISTRY }}:test
      
      - name: 'Deploy Image'
        run: |
          gcloud run deploy service-${{ github.event.pull_request.number }} --image ${{ secrets.CLOUD_REGISTRY }}:test --region us-east4 --port 8080 --allow-unauthenticated --set-env-vars context=postgres,DB_STRING="host ${{ secrets.DB_HOST }} user=postgres password=${{ secrets.DB_PASSWORD }} dbname=${{ github.event.pull_request.head.ref }} port=5432 sslmode=disable" --vpc-connector vpc-connector-serverless

      - name: Set SERVICE_URL environment variable
        id: set_service_url
        run: |
          SERVICE_URL=$(gcloud run services describe service-${{ github.event.pull_request.number }} --region us-east4 --format "value(status.url)")
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV
          echo "::set-output name=service_url::$SERVICE_URL"
          echo "SERVICE_URL=$SERVICE_URL" > url.txt

      - name: Upload the variable file
        uses: actions/upload-artifact@v3
        with:
          name: url-file
          path: url.txt

      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: ${{ github.workflow }}
          subtitle: ${{ github.event.pull_request.head.ref }}
          additionalSections: '[{"header": "Reviewer App Access", "collapsible": true, "widgets": [{"decoratedText": {"startIcon": {"knownIcon": "STAR"},"text": "${{ steps.set_service_url.outputs.service_url }}" }}] }]'

  # load-testing:
  #   if: github.event.action == 'opened' || github.event.action == 'synchronize'
  #   needs: create-cr
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: code checkout
  #       uses: actions/checkout@v2

  #     - name: Download the variable file
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: url-file
      
  #     - name: Read variable from file
  #       run: |
  #         URL=$(cat url.txt)
  #         echo "URL=${URL}" >> $GITHUB_ENV
      
  #     - name: Update ddosify json
  #       run: |
  #         sed -i.bak 's/URL/$URL/g' ddosify-data.json

  #     - name: Run load tests
  #       run: |
  #         docker pull ddosify/ddosify
  #         docker run -i --rm ddosify/ddosify ddosify -config ddosify-data.json

  #     - name: Notify Google Chat
  #       if: ${{ always() }}
  #       uses: SimonScholz/google-chat-action@main
  #       with:
  #         webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
  #         jobStatus: ${{ job.status }}
  #         title: ${{ github.workflow }}
  #         subtitle: ${{ github.event.pull_request.head.ref }}

  delete-cr:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      
      - name: 'Clean All'
        run: |
          gcloud run services delete service-${{ github.event.pull_request.number }} --region us-east4 --quiet

      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: ${{ github.workflow }}
          subtitle: ${{ github.event.pull_request.head.ref }}
