name: 'Github Demo CI/CD Pull Request'
on: 
  pull_request:
    types:
      - closed
      - opened
      - synchronize

jobs:
  container-scanning:
    if: github.event.action != 'closed'
    uses: hermes-logistic/demo-pipelines/.github/workflows/container-scanning.yaml@develop
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

  dependency-check:
    if: github.event.action != 'closed'
    uses: hermes-logistic/demo-pipelines/.github/workflows/dependency-scanner.yaml@develop
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

  code-coverage:
    if: github.event.action != 'closed'
    needs: [container-scanning, dependency-check]
    uses: hermes-logistic/demo-pipelines/.github/workflows/code-coverage.yaml@develop
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

  code-quality:
    if: github.event.action != 'closed'
    needs: [container-scanning, dependency-check]
    uses: hermes-logistic/demo-pipelines/.github/workflows/code-quality.yaml@develop
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

  go-lint:
    if: github.event.action != 'closed'
    needs: [container-scanning, dependency-check]
    permissions:
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read
    uses: hermes-logistic/demo-pipelines/.github/workflows/golangci-lint.yml@develop
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

  registry:
    if: github.event.action != 'closed'
    needs: [code-coverage, code-quality, go-lint]
    permissions:
      id-token: write
      contents: read
    uses: hermes-logistic/demo-pipelines/.github/workflows/gcp-registry-dev.yaml@develop
    secrets:
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      CLOUD_REGISTRY: '${{ secrets.CLOUD_REGISTRY }}-reviewer'
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
      IMAGE_TAG: ${{ github.sha }}

  setup-reviewer-app:
    if: github.event.action != 'closed'
    needs: registry
    permissions:
      id-token: write
      contents: read
    uses: hermes-logistic/demo-pipelines/.github/workflows/setup-reviewer.yaml@develop
    secrets:
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      CLOUD_REGISTRY: '${{ secrets.CLOUD_REGISTRY }}-reviewer'
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
      IMAGE_TAG: ${{ github.ref_name }}
      VPC_CONNECTOR: ${{ secrets.VPC_CONNECTOR }}
  
  delete-reviewer-app:
    if: github.event.action == 'closed'
    permissions:
      id-token: write
      contents: read
    uses: hermes-logistic/demo-pipelines/.github/workflows/delete-reviewer.yaml@develop
    secrets:
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
  
  load-testing:
    if: github.event.action != 'closed'
    permissions:
      id-token: write
      contents: read
    needs: setup-reviewer-app
    uses: hermes-logistic/demo-pipelines/.github/workflows/load-test.yaml@develop
    secrets:
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
